// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/logs/logs.proto

package logs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateLogReq struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	LogTime              string   `protobuf:"bytes,4,opt,name=logTime,proto3" json:"logTime,omitempty"`
	DataTitle            string   `protobuf:"bytes,5,opt,name=dataTitle,proto3" json:"dataTitle,omitempty"`
	DataFields           []byte   `protobuf:"bytes,6,opt,name=dataFields,proto3" json:"dataFields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLogReq) Reset()         { *m = CreateLogReq{} }
func (m *CreateLogReq) String() string { return proto.CompactTextString(m) }
func (*CreateLogReq) ProtoMessage()    {}
func (*CreateLogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b11fb915669ed092, []int{0}
}

func (m *CreateLogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLogReq.Unmarshal(m, b)
}
func (m *CreateLogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLogReq.Marshal(b, m, deterministic)
}
func (m *CreateLogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLogReq.Merge(m, src)
}
func (m *CreateLogReq) XXX_Size() int {
	return xxx_messageInfo_CreateLogReq.Size(m)
}
func (m *CreateLogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLogReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLogReq proto.InternalMessageInfo

func (m *CreateLogReq) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *CreateLogReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateLogReq) GetLogTime() string {
	if m != nil {
		return m.LogTime
	}
	return ""
}

func (m *CreateLogReq) GetDataTitle() string {
	if m != nil {
		return m.DataTitle
	}
	return ""
}

func (m *CreateLogReq) GetDataFields() []byte {
	if m != nil {
		return m.DataFields
	}
	return nil
}

type Error struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Details              string   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_b11fb915669ed092, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Error) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type CreateLogResp struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLogResp) Reset()         { *m = CreateLogResp{} }
func (m *CreateLogResp) String() string { return proto.CompactTextString(m) }
func (*CreateLogResp) ProtoMessage()    {}
func (*CreateLogResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b11fb915669ed092, []int{2}
}

func (m *CreateLogResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLogResp.Unmarshal(m, b)
}
func (m *CreateLogResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLogResp.Marshal(b, m, deterministic)
}
func (m *CreateLogResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLogResp.Merge(m, src)
}
func (m *CreateLogResp) XXX_Size() int {
	return xxx_messageInfo_CreateLogResp.Size(m)
}
func (m *CreateLogResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLogResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLogResp proto.InternalMessageInfo

func (m *CreateLogResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateLogReq)(nil), "velmie.wallet.logs.CreateLogReq")
	proto.RegisterType((*Error)(nil), "velmie.wallet.logs.Error")
	proto.RegisterType((*CreateLogResp)(nil), "velmie.wallet.logs.CreateLogResp")
}

func init() {
	proto.RegisterFile("rpc/logs/logs.proto", fileDescriptor_b11fb915669ed092)
}

var fileDescriptor_b11fb915669ed092 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xa9, 0x6e, 0x2b, 0x9d, 0x5d, 0x2f, 0xa3, 0x48, 0x14, 0x91, 0xb5, 0x27, 0x4f, 0x59,
	0x58, 0x0f, 0x5e, 0x45, 0x51, 0x10, 0x3c, 0x48, 0xdd, 0x93, 0x17, 0xc9, 0xb6, 0xc3, 0x12, 0xc9,
	0x92, 0x9a, 0x64, 0xeb, 0x5f, 0xf1, 0xe7, 0xda, 0x24, 0x55, 0x0b, 0x0a, 0x7b, 0x09, 0x7c, 0xf3,
	0xe6, 0xbd, 0x49, 0x26, 0x70, 0x60, 0x9a, 0x6a, 0xa6, 0xf4, 0xca, 0x86, 0x83, 0x37, 0x46, 0x3b,
	0x8d, 0xd8, 0x92, 0x5a, 0x4b, 0xe2, 0x1f, 0x42, 0x29, 0x72, 0xdc, 0x2b, 0xc5, 0x67, 0x02, 0x93,
	0x5b, 0x43, 0xc2, 0xd1, 0xa3, 0x5e, 0x95, 0xf4, 0x8e, 0x0c, 0xf6, 0xec, 0x66, 0xf9, 0x46, 0x95,
	0x63, 0xc9, 0x34, 0xb9, 0xc8, 0xcb, 0x6f, 0xc4, 0x23, 0xc8, 0x36, 0x96, 0xcc, 0x43, 0xcd, 0x76,
	0x83, 0xd0, 0x93, 0x77, 0x74, 0x51, 0x0b, 0xb9, 0x26, 0x36, 0x8a, 0x8e, 0x1e, 0xf1, 0x14, 0xf2,
	0x5a, 0x38, 0xb1, 0x90, 0x4e, 0x11, 0x4b, 0x83, 0xf6, 0x5b, 0xc0, 0x33, 0x00, 0x0f, 0xf7, 0x92,
	0x54, 0x6d, 0x59, 0xd6, 0xc9, 0x93, 0x72, 0x50, 0x29, 0xae, 0x20, 0xbd, 0x33, 0x46, 0x1b, 0x3c,
	0x84, 0xd4, 0x85, 0x88, 0x78, 0xa1, 0x08, 0x7e, 0x6c, 0x4d, 0x4e, 0x48, 0x65, 0xd9, 0x4e, 0x1c,
	0xdb, 0x63, 0x71, 0x0d, 0xfb, 0x83, 0x27, 0xd9, 0x06, 0x67, 0x90, 0x92, 0x4f, 0x0a, 0x01, 0xe3,
	0xf9, 0x31, 0xff, 0xbb, 0x08, 0x1e, 0x46, 0x95, 0xb1, 0x6f, 0xfe, 0x0a, 0xe3, 0xce, 0x6b, 0x9f,
	0xc9, 0xb4, 0xb2, 0x22, 0x7c, 0x82, 0xfc, 0x27, 0x10, 0xa7, 0xff, 0xb9, 0x87, 0x2b, 0x3c, 0x39,
	0xdf, 0xd2, 0x61, 0x9b, 0x9b, 0xec, 0x65, 0xe4, 0xab, 0xcb, 0x2c, 0xfc, 0xcc, 0xe5, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x67, 0xfe, 0x5d, 0x8b, 0xb0, 0x01, 0x00, 0x00,
}
